#+TITLE: Inventaire des orgues - charte du contributeur
#+SETUPFILE: theme-readtheorg-local.setup
#+AUTHOR: Ministère de la Culture
#+EMAIL: contact@inventaire-des-orgues.fr
#+DATE: 27 novembre 2017
#+OPTIONS: toc:t
#+LANGUAGE: fr

*Version 0.9*

Si vous voulez réagir à ce brouillon, n’hésitez pas à nous écrire à
[[mailto:contact@inventaire-des-orgues.fr][contact@inventaire-des-orgues.fr]] ou à ouvrir [[https://git.inventaire-des-orgues.fr/bzg/ido-docs/issues][un ticket]].

Vous pouvez télécharger la version [[file:data/docs/charte-du-contributeur.odt][.odt]] ou [[file:data/docs/charte-du-contributeur.docx][.docx]] de ce document pour
l’amender et nous envoyer des corrections.

* Charte du contributeur

La charte de l’utilisateur suit les principes de la [[https://inra-dam-front-resources-cdn.brainsonic.com/ressources/afile/403674-cf7ac-resource-charte-francaise-des-sciences-et-recherches-participatives.pdf][charte nationale
des sciences participatives]] (20 mars 2017).

La plateforme « Inventaire des Orgues » est un site expérimental mis
en œuvre en 2017 par le ministère de la Culture dans le cadre du
programme « [[https://entrepreneur-interet-general.etalab.gouv.fr/][Entrepreneur d’intérêt général]] » 2017, porté ensuite
conjointement par l’association [[http://www.orgue-en-france.org/][Orgue en France]], la [[http://www.ffao.com][Fédération
Francophone des Amis de l’Orgue]] et le [[http://www.culturecommunication.gouv.fr/][Ministère de la Culture]].

** Contexte

L’inventaire des orgues a pour objet :

- de présenter les données que le ministère de la Culture publie sous
  licence [[https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf][Ouverte 2.0]] sur le patrimoine des orgues, que ceux-ci soient
  inscrits ou classés au titre des monuments historiques ou étudiés
  dans l’Inventaire général du patrimoine culturel ;

- de présenter les données que les services régionaux de l’Inventaire
  du patrimoine culturel publient en Open Data sur les orgues ;

- de permettre aux amateurs d’orgues de venir enrichir ces données
  avec des compléments d’information, des corrections et des fichiers
  associés, notamment des images et des sons ;

- d’exposer ces données sous la [[https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf][licence Ouverte 2.0]] pour les contenus
  de la base de données et sous la [[https://creativecommons.org/licenses/by-sa/3.0/fr/][licence Creative Commons by-sa 3.0]]
  pour les fichiers d’images et de son, de façon à ce que différents
  acteurs puissent les consulter et les réutiliser librement.

Toute personne qui souhaite contribuer sur la plateforme « Inventaire
des Orgues » doit accepter préalablement les termes de la présente
charte.

Le contributeur reconnaît avoir pris connaissance des [[https://beta.inventaire-des-orgues.fr/mentions-legales][mentions légales]]
de la plateforme « Inventaire des Orgues ».

** Rôles et contributions

L’accès aux données mises en ligne sur la plateforme « Inventaire des
Orgues » est public depuis le site www.inventaire-des-orgues.fr.

L’utilisateur de l’inventaire entre dans l’une de ces catégories :

- Utilisateur :: Sans authentification préalable, l’utilisateur est un
     internaute qui peut accéder à tous les contenus publics de la
     plateforme.

- Contributeur :: Pour publier des contributions ou les réviser, le
     contributeur doit, au préalable, avoir créé un compte avec un nom
     d’utilisateur, un mot de passe de son choix puis s’authentifier.
     Lors des sessions suivantes, le contributeur devra se connecter
     avec ces mêmes identifiants.  Le contributeur est responsable de
     la conservation du nom d’utilisateur et du mot de passe choisis
     pour l’accès à la contribution.  Un contributeur peut, s’il en
     fait la demande, obtenir un compte sur [[https://fichiers.inventaire-des-orgues.fr/][l’outil de partage de
     fichiers]] : dans ce cas, il accepte de ne pas publier les
     documents qui sont partagés via cet espace sans être rendus
     publics.

- Administrateur :: Le statut d’administrateur est accordé par le
     comité de suivi aux contributeurs qui en font la demande.  Le
     rôle de l’administrateur n’est pas de valider scientifiquement
     les contributions mais de supprimer les contenus problématiques
     (textes, images ou sons) ou de revenir à des versions antérieures
     d’une fiche d’orgue.

- Gestionnaire de données :: Le gestionnaire de données a les mêmes
     permissions qu’un administrateur.  Il est de plus en charge de la
     promotion technique d’un contributeur au rang d’administrateur,
     si le comité de suivi lui en fait la demande.  Il accède en outre
     à des fonctionnalités d’import de données en masse.

- Membre du comité de suivi :: Le comité de suivi assure une veille
     sur la qualité des données.  Il organise l’animation éditoriale
     et communautaire de la plateforme.  Il est responsable de définir
     les évolutions fonctionnelles souhaitées pour la plateforme.  Ce
     comité est composé de membres issus des structures porteuses du
     projet : Orgue en France, la FFAO, le ministère de la Culture et
     les services régionaux de l’Inventaire général du patrimoine
     culturel.  Il peut décider de s’ouvrir à des membres issus
     d’autres structures.

Le comité de suivi se réserve le droit de refuser toute inscription
qui ne serait pas conforme à l’objet de la plateforme « Inventaire des
Orgues » et d’interdire, temporairement ou définitivement, sans mise
en demeure préalable, l’accès à la contribution.

L’adresse de messagerie requise pour l'ouverture du compte peut être
utilisée par l’équipe responsable de la plateforme afin de contacter
le contributeur dans le cadre de sa participation à l’expérimentation.

Le contributeur peut proposer autant de modifications et de nouveaux
contenus qu’il le souhaite.

Toutes les contributions, soumises ou révisées, sur la plateforme sont
rendues publiques sous [[https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf][licence Ouverte 2.0]] et sous [[https://creativecommons.org/licenses/by-sa/3.0/fr/][licence Creative
Commons by-sa 3.0]].

** Règles de Contribution

En participant à la plateforme « Inventaire des Orgues », et en créant
un compte, le contributeur s’engage notamment :

1. à indiquer dès l’inscription, et dans la mesure du possible, un nom
   d’utilisateur permettant l’identification claire du contributeur ;

2. à respecter les obligations légales [lien vers les mentions légales
   sur le site] en matière de propriété intellectuelle ;

3. à introduire des modifications en citant des sources fiables et
   vérifiables ;

4. à apporter des contributions objectives, utiles, en rapport avec le
   sujet abordé, et à participer aux débats de manière constructive,
   dans le respect de la diversité des opinions ;

5. à n’exprimer aucun propos illicites, diffamants, injurieux,
   obscènes, discriminatoires, menaçants ou contraires à l’esprit du
   projet ;

6. à ne pas publier de publicité ou exercer d’activité commerciale ;

7. à s'exprimer dans un langage correct et accessible, en respectant
   la courtoisie des échanges ;

8. à publier ses contributions à la base de données sous [[https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf][la licence
   Ouverte 2.0]] ; cette licence requiert que toute réutilisation d’une
   donnée de l’inventaire national des orgues cite son auteur et sa
   source et permet à quiconque de réutiliser les données, y compris à
   des fins commerciales ; à publier ses fichiers d’images et de sons
   sous la [[https://creativecommons.org/licenses/by-sa/3.0/fr/][licence Creative Commons by-sa 3.0]] ; requiert que toute
   réutilisation d’un fichier d’image ou de son cite son auteur et sa
   source et permet à quiconque de réutiliser le fichier, y compris à
   des fins commerciales, à condition que le fichier réutilisé soit
   placé sous la même licence.

L’équipe responsable de la plateforme est susceptible de supprimer ou
modérer une contribution sans préavis, si les règles mentionnées dans
la charte ne sont pas respectées.

** Données personnelles et confidentialité

Les contributeurs doivent s’enregistrer sous leurs prénom et nom
usuels.

L’identité du contributeur apparaîtra selon les noms et prénoms
renseignés lors de son inscription à la plateforme « Inventaire des
Orgues ».

Les messages qui pourraient être envoyés aux contributeurs seront
envoyés via un dispositif garantissant le non-piratage des adresses
électroniques.

Comme l’indiquent les mentions légales, les données personnelles du
contributeur (nom, prénom, adresse électronique) ne sont collectées
que pour permettre le bon fonctionnement du site et ne sont partagées
qu’avec les structures porteuses du projet.

