site_name: Documentation de l'inventaire des orgues
site_url: https://docs.inventaire-des-orgues.fr/
site_description: Documentation de l'inventaire des orgues
site_author: Gwilherm Poullennec

repo_url: 

theme: mkdocs

nav:
    - Home: index.md
    - Questions/réponses: faq.md
    - Description d'un orgue : fiche-orgue.md
    - Origine des données:
        - Etat et collectivités: donnees_etatcollectivites.md
        - Sites Internet: donnees_sites.md
        - Livres d'inventaires: donnees_livres.md
    - About: about.md
